from abc import ABC, abstractmethod
from typing import Dict, Any, List

class IClient(ABC):
    @abstractmethod
    async def futures_exchange_info(self) -> Dict[str, Any]: ...

    @abstractmethod
    async def futures_mark_price(self, symbol: str) -> Dict[str, Any]: ...

    @abstractmethod
    async def futures_create_order(self, **kwargs) -> Dict[str, Any]: ...
    
    @abstractmethod
    async def futures_cancel_all_open_orders(self, symbol: str) -> Any: ...

    @abstractmethod
    async def futures_cancel_order(self, symbol: str, orderId: int) -> Any: ...

    @abstractmethod
    async def futures_get_open_orders(self, symbol: str) -> List[Dict[str, Any]]: ...

    @abstractmethod
    async def futures_position_information(self, symbol: str) -> List[Dict[str, Any]]: ...

    @abstractmethod
    async def futures_account_balance(self) -> List[Dict[str, Any]]: ...

    @abstractmethod
    async def futures_klines(self, symbol: str, interval: str, limit: int) -> List[Any]: ...

    @abstractmethod
    async def futures_change_margin_type(self, symbol: str, marginType: str) -> Any: ...

    @abstractmethod
    async def futures_change_leverage(self, symbol: str, leverage: int) -> Any: ...
    
    @abstractmethod
    async def close_connection(self): ...
